/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.edit;

import java.awt.Component;
import java.awt.Graphics;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import services.EditCuloareService;
import services.interfaces.EventConfirmationListener;
import services.interfaces.FormListenerInterface;

/**
 *
 * @author Manel
 */
public class EditCuloareForm extends javax.swing.JFrame implements FormListenerInterface {

    EditCuloareService service;

    /**
     * Creates new form EditCuloriForm
     *
     * @param service
     */
    public EditCuloareForm(EditCuloareService service) {
        initComponents();
        this.service = service;
        /*jPanel3.add(new ImageHolder(Paths.get("c:", "users", "manel", "desktop", "argint_2.jpg")));
        jPanel3.add(new ImageHolder(Paths.get("c:", "users", "manel", "desktop", "argint_2.jpg")));
        jPanel3.add(new ImageHolder(Paths.get("c:", "users", "manel", "desktop", "argint_2.jpg")));
        jPanel3.add(new ImageHolder(Paths.get("c:", "users", "manel", "desktop", "argint_2.jpg")));
        jPanel3.add(new ImageHolder(Paths.get("c:", "users", "manel", "desktop", "argint_2.jpg")));
        jPanel3.add(new ImageHolder(Paths.get("c:", "users", "manel", "desktop", "argint_2.jpg")));
        jPanel3.add(new ImageHolder(Paths.get("c:", "users", "manel", "desktop", "argint_2.jpg")));
        jPanel3.add(new ImageHolder(Paths.get("c:", "users", "manel", "desktop", "argint_2.jpg")));
        jPanel3.add(new ImageHolder(Paths.get("c:", "users", "manel", "desktop", "argint_2.jpg")));
        jPanel3.add(new ImageHolder(Paths.get("c:", "users", "manel", "desktop", "argint_2.jpg")));*/
    }

    public EditCuloareService getService() {
        return service;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeCuloare = new views.PlaceholderTextField();
        englezaCuloare = new views.PlaceholderTextField();
        maghiaraCuloare = new views.PlaceholderTextField();
        germanaCuloare = new views.PlaceholderTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        culoarePaletar = new javax.swing.JButton(){
            @Override
            public void paintComponent(Graphics g){
                super.paintComponent(g);
                g.setColor(getBackground());
                g.fillRect(0,0,15,15);
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("Unghiuri : ");
        jPanel1.add(jLabel1);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel1.add(jSpinner1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);

        culoarePaletar.setText("Culoare paletar");
        jPanel1.add(culoarePaletar);

        jScrollPane2.setViewportView(jPanel3);
        jScrollPane2.getHorizontalScrollBar().setUnitIncrement(16);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeCuloare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(englezaCuloare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maghiaraCuloare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(germanaCuloare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeCuloare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(englezaCuloare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maghiaraCuloare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(germanaCuloare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        numeCuloare.setPlaceholder("Nume culoare");
        englezaCuloare.setPlaceholder("Traducerea in engleza");
        maghiaraCuloare.setPlaceholder("Traducerea in maghiara");
        germanaCuloare.setPlaceholder("Traducerea in germana");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listener.onCancel();
        listener.onFinish(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            service.moveAllImagesToRightFolder(jPanel3.getComponents());
            service.mapNewImagesToDatabase(jPanel3.getComponents());
            service.mapAllOtherFieldsToObject();
            service.mapAllImagesWithBaseColorName();
            listener.onConfirm(service.getCuloareCopy());
            listener.onFinish(service.getCuloareCopy());
        } catch (IOException ex) {
            Logger.getLogger(EditCuloareForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        if (service.getApplicator().isAutocompleteDone()) {
            service.unghiuriChanged((int) jSpinner1.getValue());
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton culoarePaletar;
    public views.PlaceholderTextField englezaCuloare;
    public views.PlaceholderTextField germanaCuloare;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSpinner jSpinner1;
    public views.PlaceholderTextField maghiaraCuloare;
    public views.PlaceholderTextField numeCuloare;
    // End of variables declaration//GEN-END:variables

    EventConfirmationListener listener;

    @Override
    public void setListener(EventConfirmationListener e) {
        this.listener = e;
    }
}
